### ISSUE TITLE
Diacritical signs or accents

### ISSUE THREAD

**Issue by Miroul** [trgkanki/word_autocomplete#4] opened 2020-05-05 08:52 UTC
The add-on doesn't work for words with diacritical signs.

**Comment by thiswillbeyourgithub** [comment] 2020-05-27 11:47
I was able to make progress by changing the regex from the init file into this 

alphaNumeric = re.compile("[a-zA-ZÀ-ú][a-zA-Z0-9À-ú]{2,15}")


unfortunately there seems to be an issue where when autocompleting and finding words. I think the issue is with anki's search engine :/

**Comment by thiswillbeyourgithub** [comment] 2020-05-27 18:46
After using it for the last hours I'll use this :

`alphaNumeric = re.compile("[a-zA-ZÀ-ú]{2,20}")`
(this won't match words that have numbers in them but it makes it faster)

 `self.web.eval("wordSet = [" + ''.join('"%r", ' % w for w in wordSet).replace("'",'') + "]")`


I replaced %s with %r, and added .replace to strip the `'` that were around the output.


It's quite functionnal, it can complete words with accent but if you enter an accent yourself it will consider it as the beginning of a word.

For example : security in french is sécurité, if you type séc... it will look for word beginning with c...

**Comment by phu54321** [comment] 2020-06-02 05:39
Check if new release fixes this

**Comment by thiswillbeyourgithub** [comment] 2020-06-02 18:05
Is the new release available on anki 2.1.22 ? I had troubles with the latest version so i went back to 22.

**Comment by thiswillbeyourgithub** [comment] 2020-06-03 15:42
I got the new version.

It doesn't work exactly right. Let's take the word allégorie for example.

If I type alle, it will offer to complete allégorie and works as expected
if I type allé, it will offer allégorie as well but won't paste it right : I end up with alléallégorie. Or catécatécholamine for caté.

It seems anki doesn't do well with accents. I think a doable workaround would be to delete the entered word just before pasting the right one if the beginning of the typed word contains an accent.

**Comment by thiswillbeyourgithub** [comment] 2020-08-11 12:37
Thanks A LOT for your recent updates! 

I noticed that this issue was marked as closed even though the issue is still here. I think only you can reopen it.

Have a nice day!

**Comment by phu54321** [comment] 2020-08-11 13:43
Missed your comment(https://github.com/trgkanki/word_autocomplete/issues/4#issuecomment-638280748). Sorry.
Re-opened the issue

**Closed** 2020-09-13 18:57 UTC
